#### Get the marginal varianve matrix using the equation in the paper

In [17]:
import pickle
import numpy as np
from scipy.linalg import null_space

In [18]:

# Load matrix from file
with open('matrix_arnsberg.pkl', 'rb') as f:
    Q = pickle.load(f)

print("Loaded matrix:")
print(Q)

Loaded matrix:
[[ 3 -1 -1  0  0 -1  0  0  0  0  0  0]
 [-1  4 -1 -1  0  0  0  0  0  0  0 -1]
 [-1 -1  4 -1  0  0  0 -1  0  0  0  0]
 [ 0 -1 -1  4  0  0  0 -1  0  0  0 -1]
 [ 0  0  0  0  2  0  0  0  0  0 -1 -1]
 [-1  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  4 -1 -1 -1 -1  0]
 [ 0  0 -1 -1  0  0 -1  6 -1  0 -1 -1]
 [ 0  0  0  0  0  0 -1 -1  3 -1  0  0]
 [ 0  0  0  0  0  0 -1  0 -1  2  0  0]
 [ 0  0  0  0 -1  0 -1 -1  0  0  4 -1]
 [ 0 -1  0 -1 -1  0  0 -1  0  0 -1  5]]


In [19]:
# get the determinant of the matrix
det = np.linalg.det(Q)
det

-8.130015260572453e-12

##### Null space of matrix Q

In [20]:
# Compute the Null Space V of Q
V = null_space(Q)
V

array([[0.28867513],
       [0.28867513],
       [0.28867513],
       [0.28867513],
       [0.28867513],
       [0.28867513],
       [0.28867513],
       [0.28867513],
       [0.28867513],
       [0.28867513],
       [0.28867513],
       [0.28867513]])

In [21]:
Q.dot(V)

array([[-5.55111512e-17],
       [ 4.44089210e-16],
       [ 5.55111512e-17],
       [ 2.77555756e-16],
       [ 4.99600361e-16],
       [-1.66533454e-16],
       [ 0.00000000e+00],
       [-7.21644966e-16],
       [ 1.66533454e-16],
       [-3.33066907e-16],
       [-6.66133815e-16],
       [ 2.22044605e-16]])

In [22]:
b = null_space(V.transpose())

In [23]:
# find covariance of matrix b
cov_b = np.cov(b)

### Find the Cov(b| V^T b=0)

In [24]:
A = cov_b.dot(V)

In [25]:
# inverse of A
B = np.linalg.inv(V.transpose().dot(cov_b).dot(V))

In [26]:
C = V.transpose().dot(cov_b)

In [27]:
equation = cov_b - A.dot(B).dot(C)

In [28]:
# Extract Marginal Variances (diagonal elements of the variance-covariance matrix)
marginal_variances = np.diag(equation)

print("Marginal Variances:", marginal_variances)

Marginal Variances: [4.56060211e-32 9.09090909e-02 9.09090909e-02 9.09090909e-02
 9.09090909e-02 9.09090909e-02 9.09090909e-02 9.09090909e-02
 9.09090909e-02 9.09090909e-02 9.09090909e-02 9.09090909e-02]


In [29]:
# Format and print the marginal variances
print("Marginal Variances:")
for variance in marginal_variances:
    print("{:.12f}".format(variance))

Marginal Variances:
0.000000000000
0.090909090909
0.090909090909
0.090909090909
0.090909090909
0.090909090909
0.090909090909
0.090909090909
0.090909090909
0.090909090909
0.090909090909
0.090909090909


In [30]:
geometric_mean = np.exp(np.mean(np.log(marginal_variances)))
geometric_mean

0.00027142002567738527