#### Null space - For extreamly small values

In [25]:
import pickle
import numpy as np


In [26]:

# Load matrix from file
with open('matrix.pkl', 'rb') as f:
    Q = pickle.load(f)

print("Loaded matrix:")
print(Q)

Loaded matrix:
[[ 3 -1 -1  0  0 -1  0  0  0  0  0  0]
 [-1  4 -1 -1  0  0  0  0  0  0  0 -1]
 [-1 -1  4 -1  0  0  0 -1  0  0  0  0]
 [ 0 -1 -1  4  0  0  0 -1  0  0  0 -1]
 [ 0  0  0  0  2  0  0  0  0  0 -1 -1]
 [-1  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  4 -1 -1 -1 -1  0]
 [ 0  0 -1 -1  0  0 -1  6 -1  0 -1 -1]
 [ 0  0  0  0  0  0 -1 -1  3 -1  0  0]
 [ 0  0  0  0  0  0 -1  0 -1  2  0  0]
 [ 0  0  0  0 -1  0 -1 -1  0  0  4 -1]
 [ 0 -1  0 -1 -1  0  0 -1  0  0 -1  5]]


In [27]:
print(type(Q))
print(type(Q[0,0]))

<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [28]:
# get the determinant of the matrix
det = np.linalg.det(Q)
det

-8.130015260572453e-12

##### Precision matrix regularized

In [29]:
# Make the Precision Matrix Regular (if necessary)
epsilon = 1e-6  # small term to add to the diagonal
Q_regularized = Q + epsilon * np.eye(Q.shape[0])

In [30]:
Q_regularized

array([[ 3.000001, -1.      , -1.      ,  0.      ,  0.      , -1.      ,
         0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [-1.      ,  4.000001, -1.      , -1.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ,  0.      ,  0.      , -1.      ],
       [-1.      , -1.      ,  4.000001, -1.      ,  0.      ,  0.      ,
         0.      , -1.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      , -1.      , -1.      ,  4.000001,  0.      ,  0.      ,
         0.      , -1.      ,  0.      ,  0.      ,  0.      , -1.      ],
       [ 0.      ,  0.      ,  0.      ,  0.      ,  2.000001,  0.      ,
         0.      ,  0.      ,  0.      ,  0.      , -1.      , -1.      ],
       [-1.      ,  0.      ,  0.      ,  0.      ,  0.      ,  1.000001,
         0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         4.000001, -1.      , -1

In [31]:
# get the determinant of the matrix
det = np.linalg.det(Q_regularized)
det

0.15616887967188134