#### Null space - For extreamly small values

In [2]:
import pickle
import numpy as np
from scipy.linalg import null_space

In [3]:

# Load matrix from file
with open('matrix_mittelfranken.pkl', 'rb') as f:
    Q = pickle.load(f)

print("Q matrix which we got from adjacencies:")
print(Q)

Q matrix which we got from adjacencies:
[[ 1 -1  0  0  0  0  0  0  0  0  0  0]
 [-1  5  0  0  0 -1  0 -1  0 -1  0 -1]
 [ 0  0  5 -1  0 -1 -1 -1 -1  0  0  0]
 [ 0  0 -1  4 -1 -1  0  0 -1  0  0  0]
 [ 0  0  0 -1  3 -1  0  0 -1  0  0  0]
 [ 0 -1 -1 -1 -1  7  0 -1 -1 -1  0  0]
 [ 0  0 -1  0  0  0  3  0 -1 -1  0  0]
 [ 0 -1 -1  0  0 -1  0  3  0  0  0  0]
 [ 0  0 -1 -1 -1 -1 -1  0  7 -1 -1  0]
 [ 0 -1  0  0  0 -1 -1  0 -1  6 -1 -1]
 [ 0  0  0  0  0  0  0  0 -1 -1  2  0]
 [ 0 -1  0  0  0  0  0  0  0 -1  0  2]]


In [6]:
print(Q.shape)
print(type(Q))
print(type(Q[0,0]))

(12, 12)
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [7]:
print("The Rank of the Q Matrix: ", np.linalg.matrix_rank(Q))

The Rank of the Q Matrix:  12


In [8]:
# get the determinant of the matrix
det = np.linalg.det(Q)
det

751167.9999999993

##### Precision matrix regularized

In [9]:
# Make the Precision Matrix Regularized
epsilon = 1e-6  # small term to add to the diagonal
Q_regularized = Q + epsilon * np.eye(Q.shape[0])

In [10]:
Q_regularized=Q

In [11]:
Q_regularized

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 5, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 5, 1, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 1, 4, 1, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 3, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 1, 7, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 3, 0, 1, 1, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 3, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 7, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 1, 6, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2]])

In [12]:
print("The Rank of the Q regulized Matrix: ", np.linalg.matrix_rank(Q_regularized))

# get the determinant of the matrix
det = np.linalg.det(Q_regularized)
print("The determinant of the regularized matrix: ", det)

# Compute the Null Space V of Q
V = null_space(Q_regularized)
print("The Null Space of the regularized matrix: ")
V


The Rank of the Q regulized Matrix:  12
The determinant of the regularized matrix:  751167.9999999993
The Null Space of the regularized matrix: 


array([], shape=(12, 0), dtype=float64)

In [13]:
# checking the null space matrix
Q_regularized.dot(V)

array([], shape=(12, 0), dtype=float64)

In [14]:
# create 12 by 1 matrix
V = np.ones((Q.shape[0], 1))

In [15]:
# checking the null space matrix
Q_regularized.dot(V)

array([[ 2.],
       [10.],
       [10.],
       [ 8.],
       [ 6.],
       [14.],
       [ 6.],
       [ 6.],
       [14.],
       [12.],
       [ 4.],
       [ 4.]])

____________________

In [16]:
# b matrix
b = null_space(V.transpose())

In [17]:
# find covariance of matrix b
cov_b = np.cov(b)

### Find the Cov(b| V^T b=0)

In [18]:
A = cov_b.dot(V)

In [19]:
# inverse of A
B = np.linalg.inv(V.transpose().dot(cov_b).dot(V))

In [20]:
C = V.transpose().dot(cov_b)

In [21]:
equation = cov_b - A.dot(B).dot(C)

In [22]:
cov_b_VTb = np.cov(equation)

In [23]:
# Extract Marginal Variances (diagonal elements of the variance-covariance matrix)
marginal_variances = np.diag(cov_b_VTb)

print("Marginal Variances:", marginal_variances)

Marginal Variances: [1.23046120e-66 8.26446281e-04 8.26446281e-04 8.26446281e-04
 8.26446281e-04 8.26446281e-04 8.26446281e-04 8.26446281e-04
 8.26446281e-04 8.26446281e-04 8.26446281e-04 8.26446281e-04]


In [30]:
# Format and print the marginal variances
print("Marginal Variances:")
for variance in marginal_variances:
    print("{:.12f}".format(variance))

Marginal Variances:
0.000000000000
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281


In [24]:
np.log(np.diag(cov_b_VTb))

array([-151.76322708,   -7.09837564,   -7.09837564,   -7.09837564,
         -7.09837564,   -7.09837564,   -7.09837564,   -7.09837564,
         -7.09837564,   -7.09837564,   -7.09837564,   -7.09837564])

In [25]:
# get the sum of the diagonal of the covariance matrix
sum_diag = np.exp(np.sum(np.log(np.diag(cov_b_VTb))))
sum_diag

1.511572043500573e-100

In [128]:
import sys

eps = sys.float_info.epsilon
print("Machine epsilon:", eps)

Machine epsilon: 2.220446049250313e-16
