#### Null space - For extreamly small values

In [8]:
import pickle
import numpy as np
from scipy.linalg import null_space

In [2]:

# Load matrix from file
with open('matrix_arnsberg.pkl', 'rb') as f:
    Q = pickle.load(f)

print("Loaded matrix:")
print(Q)

Loaded matrix:
[[ 1 -1  0  0  0  0  0  0  0  0  0  0]
 [-1  5  0  0  0 -1  0 -1  0 -1  0 -1]
 [ 0  0  5 -1  0 -1 -1 -1 -1  0  0  0]
 [ 0  0 -1  4 -1 -1  0  0 -1  0  0  0]
 [ 0  0  0 -1  3 -1  0  0 -1  0  0  0]
 [ 0 -1 -1 -1 -1  7  0 -1 -1 -1  0  0]
 [ 0  0 -1  0  0  0  3  0 -1 -1  0  0]
 [ 0 -1 -1  0  0 -1  0  3  0  0  0  0]
 [ 0  0 -1 -1 -1 -1 -1  0  7 -1 -1  0]
 [ 0 -1  0  0  0 -1 -1  0 -1  6 -1 -1]
 [ 0  0  0  0  0  0  0  0 -1 -1  2  0]
 [ 0 -1  0  0  0  0  0  0  0 -1  0  2]]


In [26]:
print(Q.shape)
print(type(Q))
print(type(Q[0,0]))

(12, 12)
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [4]:
# get the determinant of the matrix
det = np.linalg.det(Q)
det

6.559690316036448e-11

##### Precision matrix regularized

In [21]:
# Make the Precision Matrix Regular (if necessary)
epsilon = 1e-1  # small term to add to the diagonal
Q_regularized = Q + epsilon * np.eye(Q.shape[0])

In [22]:
Q_regularized

array([[ 1.1, -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ],
       [-1. ,  5.1,  0. ,  0. ,  0. , -1. ,  0. , -1. ,  0. , -1. ,  0. ,
        -1. ],
       [ 0. ,  0. ,  5.1, -1. ,  0. , -1. , -1. , -1. , -1. ,  0. ,  0. ,
         0. ],
       [ 0. ,  0. , -1. ,  4.1, -1. , -1. ,  0. ,  0. , -1. ,  0. ,  0. ,
         0. ],
       [ 0. ,  0. ,  0. , -1. ,  3.1, -1. ,  0. ,  0. , -1. ,  0. ,  0. ,
         0. ],
       [ 0. , -1. , -1. , -1. , -1. ,  7.1,  0. , -1. , -1. , -1. ,  0. ,
         0. ],
       [ 0. ,  0. , -1. ,  0. ,  0. ,  0. ,  3.1,  0. , -1. , -1. ,  0. ,
         0. ],
       [ 0. , -1. , -1. ,  0. ,  0. , -1. ,  0. ,  3.1,  0. ,  0. ,  0. ,
         0. ],
       [ 0. ,  0. , -1. , -1. , -1. , -1. , -1. ,  0. ,  7.1, -1. , -1. ,
         0. ],
       [ 0. , -1. ,  0. ,  0. ,  0. , -1. , -1. ,  0. , -1. ,  6.1, -1. ,
        -1. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -1. , -1. ,  2.1,
         0. ],
       [ 0. , -1. ,  

In [23]:
# get the determinant of the matrix
det = np.linalg.det(Q_regularized)
det

127291.43515456119

In [24]:
# Compute the Null Space V of Q
V = null_space(Q_regularized)
V

array([], shape=(12, 0), dtype=float64)

In [31]:
# Compute the Null Space V of Q
V = null_space(Q)
V

array([[-0.28867513],
       [-0.28867513],
       [-0.28867513],
       [-0.28867513],
       [-0.28867513],
       [-0.28867513],
       [-0.28867513],
       [-0.28867513],
       [-0.28867513],
       [-0.28867513],
       [-0.28867513],
       [-0.28867513]])

In [11]:
Q.dot(V)

array([[-2.77555756e-16],
       [ 1.11022302e-16],
       [ 1.83186799e-15],
       [-6.10622664e-16],
       [ 9.43689571e-16],
       [-9.99200722e-16],
       [-4.44089210e-16],
       [ 5.55111512e-17],
       [-7.77156117e-16],
       [ 7.77156117e-16],
       [ 1.11022302e-16],
       [-4.44089210e-16]])

In [33]:
null_space(V.transpose())

array([[-0.28867513, -0.28867513, -0.28867513, -0.28867513, -0.28867513,
        -0.28867513, -0.28867513, -0.28867513, -0.28867513, -0.28867513,
        -0.28867513],
       [ 0.9353341 , -0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 ,
        -0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 ,
        -0.0646659 ],
       [-0.0646659 ,  0.9353341 , -0.0646659 , -0.0646659 , -0.0646659 ,
        -0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 ,
        -0.0646659 ],
       [-0.0646659 , -0.0646659 ,  0.9353341 , -0.0646659 , -0.0646659 ,
        -0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 ,
        -0.0646659 ],
       [-0.0646659 , -0.0646659 , -0.0646659 ,  0.9353341 , -0.0646659 ,
        -0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 ,
        -0.0646659 ],
       [-0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 ,  0.9353341 ,
        -0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 , -0.0646659 ,
        -0.064

In [34]:
b = null_space(V.transpose())

In [36]:
# find covariance of matrix b
cov_b = np.cov(b)

In [38]:
cov_b.shape

(12, 12)

In [39]:
cov_b

array([[ 2.46519033e-32, -1.00929366e-17,  2.87648693e-17,
        -4.54182146e-18,  2.32137542e-17, -1.00929366e-17,
        -4.54182146e-18, -4.54182146e-18, -4.54182146e-18,
         6.56040878e-18,  6.56040878e-18, -2.67462820e-17],
       [-1.00929366e-17,  9.09090909e-02, -9.09090909e-03,
        -9.09090909e-03, -9.09090909e-03, -9.09090909e-03,
        -9.09090909e-03, -9.09090909e-03, -9.09090909e-03,
        -9.09090909e-03, -9.09090909e-03, -9.09090909e-03],
       [ 2.87648693e-17, -9.09090909e-03,  9.09090909e-02,
        -9.09090909e-03, -9.09090909e-03, -9.09090909e-03,
        -9.09090909e-03, -9.09090909e-03, -9.09090909e-03,
        -9.09090909e-03, -9.09090909e-03, -9.09090909e-03],
       [-4.54182146e-18, -9.09090909e-03, -9.09090909e-03,
         9.09090909e-02, -9.09090909e-03, -9.09090909e-03,
        -9.09090909e-03, -9.09090909e-03, -9.09090909e-03,
        -9.09090909e-03, -9.09090909e-03, -9.09090909e-03],
       [ 2.32137542e-17, -9.09090909e-03, -9.0909090

### Find the Cov(b| V^T b=0)

In [40]:
A = cov_b.dot(V)

In [41]:
# inverse of A
B = np.linalg.inv(V.transpose().dot(cov_b).dot(V))

In [42]:
C = V.transpose().dot(cov_b)

In [45]:
equation = cov_b - A.dot(B).dot(C)

In [46]:
cov_b_VTb = np.cov(equation)

In [49]:
# Extract Marginal Variances (diagonal elements of the variance-covariance matrix)
marginal_variances = np.diag(cov_b_VTb)

print("Marginal Variances:", marginal_variances)

Marginal Variances: [2.23089538e-34 8.26446281e-04 8.26446281e-04 8.26446281e-04
 8.26446281e-04 8.26446281e-04 8.26446281e-04 8.26446281e-04
 8.26446281e-04 8.26446281e-04 8.26446281e-04 8.26446281e-04]


In [52]:
# Format and print the marginal variances
print("Marginal Variances:")
for variance in marginal_variances:
    print("{:.12f}".format(variance))

Marginal Variances:
0.000000000000
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281
0.000826446281


In [47]:
# get the sum of the diagonal of the covariance matrix
sum_diag = np.sum(np.diag(cov_b_VTb))
sum_diag

0.009090909090909085