#### Scaling main - Mittelfranken

In [2]:
import pickle
import numpy as np
from scipy.linalg import null_space

In [3]:
# Load matrix from file
with open('matrix_mittelfranken.pkl', 'rb') as f:
    Q = pickle.load(f)

print("Q matrix which we got from adjacencies:")
print(Q)

Q matrix which we got from adjacencies:
[[ 1 -1  0  0  0  0  0  0  0  0  0  0]
 [-1  5  0  0  0 -1  0 -1  0 -1  0 -1]
 [ 0  0  5 -1  0 -1 -1 -1 -1  0  0  0]
 [ 0  0 -1  4 -1 -1  0  0 -1  0  0  0]
 [ 0  0  0 -1  3 -1  0  0 -1  0  0  0]
 [ 0 -1 -1 -1 -1  7  0 -1 -1 -1  0  0]
 [ 0  0 -1  0  0  0  3  0 -1 -1  0  0]
 [ 0 -1 -1  0  0 -1  0  3  0  0  0  0]
 [ 0  0 -1 -1 -1 -1 -1  0  7 -1 -1  0]
 [ 0 -1  0  0  0 -1 -1  0 -1  6 -1 -1]
 [ 0  0  0  0  0  0  0  0 -1 -1  2  0]
 [ 0 -1  0  0  0  0  0  0  0 -1  0  2]]


In [4]:
# get the determinant of the matrix
det = np.linalg.det(Q)
det

6.559690316036448e-11

#### Compute the generalized inverse
###### The generalized inverse of a matrix, also known as the Moore-Penrose inverse (oseudo Inverse)

In [5]:
# Compute SVD of Q
U, S, Vt = np.linalg.svd(Q)

In [6]:
# get the machine epsilon
eps = np.finfo(float).eps
tol = np.sqrt(eps)
tol

1.4901161193847656e-08

In [7]:
# Calculate inverse of singular values
S_inv = np.where(S > tol, 1/S, 0)

In [8]:
# Construct the generalized inverse
Q_inv = Vt.T @ np.diag(S_inv) @ U.T

In [9]:
print("Generalized Inverse of Q:")
print(Q_inv)

Generalized Inverse of Q:
[[ 1.05878351e+00  1.42116845e-01 -1.42710374e-01 -1.61063011e-01
  -1.65651170e-01 -1.01535805e-01 -1.54777470e-01 -6.18208890e-02
  -1.51021361e-01 -8.72673431e-02 -1.60811019e-01 -1.42419156e-02]
 [ 1.42116845e-01  2.25450178e-01 -5.93770405e-02 -7.77296774e-02
  -8.23178366e-02 -1.82024717e-02 -7.14441370e-02  2.15124443e-02
  -6.76880274e-02 -3.93400975e-03 -7.74776852e-02  6.90914177e-02]
 [-1.42710374e-01 -5.93770405e-02  2.14291205e-01  4.31457339e-02
   3.59366184e-04  1.92445148e-02  4.01028096e-02  3.02751152e-02
   2.20211832e-02 -3.26706256e-02 -4.69913879e-02 -8.76904997e-02]
 [-1.61063011e-01 -7.77296774e-02  4.31457339e-02  2.78173596e-01
   8.69305611e-02  3.01039507e-02 -1.57919052e-02 -2.92711087e-02
   3.58474703e-02 -4.30355864e-02 -4.52607247e-02 -1.02049299e-01]
 [-1.65651170e-01 -8.23178366e-02  3.59366184e-04  8.69305611e-02
   3.58573360e-01  3.28188097e-02 -2.97655839e-02 -4.41576647e-02
   3.93040420e-02 -4.56268265e-02 -4.48280589e

### Compute generalized variance - using Q Inv

In [10]:
generalized_variance = np.exp(np.mean(np.log(np.diag(Q_inv))))  # equation in the paper use daba as 1
generalized_variance #fac in R code

0.3002226098106932

In [11]:
marginal_variances = np.diag(Q_inv/generalized_variance)
marginal_variances

array([3.52666147, 0.75094337, 0.71377437, 0.92655778, 1.19435828,
       0.47481271, 1.11742305, 1.09756368, 0.52048608, 0.55637229,
       1.65956464, 1.70813615])

In [12]:
geometric_mean = np.exp(np.mean(np.log(marginal_variances)))
geometric_mean

1.0

In [13]:
QQ = generalized_variance*Q # this is completely different!
print(np.diag(QQ))

[0.30022261 1.50111305 1.50111305 1.20089044 0.90066783 2.10155827
 0.90066783 0.90066783 2.10155827 1.80133566 0.60044522 0.60044522]
