#### Scaling main - Arnsberg

In [15]:
import pickle
import numpy as np
from scipy.linalg import null_space

In [17]:
# Load matrix from file
with open('matrix_arnsberg.pkl', 'rb') as f:
    Q = pickle.load(f)

print("Q matrix which we got from adjacencies:")
print(Q)

Q matrix which we got from adjacencies:
[[ 3 -1 -1  0  0 -1  0  0  0  0  0  0]
 [-1  4 -1 -1  0  0  0  0  0  0  0 -1]
 [-1 -1  4 -1  0  0  0 -1  0  0  0  0]
 [ 0 -1 -1  4  0  0  0 -1  0  0  0 -1]
 [ 0  0  0  0  2  0  0  0  0  0 -1 -1]
 [-1  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  4 -1 -1 -1 -1  0]
 [ 0  0 -1 -1  0  0 -1  6 -1  0 -1 -1]
 [ 0  0  0  0  0  0 -1 -1  3 -1  0  0]
 [ 0  0  0  0  0  0 -1  0 -1  2  0  0]
 [ 0  0  0  0 -1  0 -1 -1  0  0  4 -1]
 [ 0 -1  0 -1 -1  0  0 -1  0  0 -1  5]]


In [18]:
# get the determinant of the matrix
det = np.linalg.det(Q)
det

-8.130015260572453e-12

#### Compute the generalized inverse

In [19]:
# Compute SVD of Q
U, S, Vt = np.linalg.svd(Q)

In [20]:
# get the machine epsilon
eps = np.finfo(float).eps
tol = np.sqrt(eps)
tol

1.4901161193847656e-08

In [21]:
# Calculate inverse of singular values
S_inv = np.where(S > tol, 1/S, 0)

In [22]:
# Construct the generalized inverse
Q_inv = Vt.T @ np.diag(S_inv) @ U.T

In [23]:
print("Generalized Inverse of Q:")
print(Q_inv)

Generalized Inverse of Q:
[[ 0.52957872  0.11550542  0.1103187  -0.01208794 -0.16325207  0.44624539
  -0.20543741 -0.10838808 -0.21661768 -0.25269421 -0.16071634 -0.08245447]
 [ 0.11550542  0.30516655  0.09251095  0.07383875 -0.06833506  0.03217208
  -0.13126729 -0.04113359 -0.14521381 -0.17990722 -0.07548121  0.02214442]
 [ 0.1103187   0.09251095  0.29479311  0.06865203 -0.09150242  0.02698536
  -0.11294087 -0.00897591 -0.12135489 -0.15881455 -0.07928481 -0.0203867 ]
 [-0.01208794  0.07383875  0.06865203  0.27957872 -0.03825207 -0.09542128
  -0.08043741  0.01661192 -0.09161768 -0.12769421 -0.03571634  0.04254553]
 [-0.16325207 -0.06833506 -0.09150242 -0.03825207  0.57914073 -0.24658541
  -0.03150934 -0.01283714 -0.07404046 -0.09444156  0.13861515  0.10299965]
 [ 0.44624539  0.03217208  0.02698536 -0.09542128 -0.24658541  1.36291206
  -0.28877075 -0.19172142 -0.29995101 -0.33602755 -0.24404968 -0.16578781]
 [-0.20543741 -0.13126729 -0.11294087 -0.08043741 -0.03150934 -0.28877075
   0.3

### Compute generalized variance - using Q Inv

In [31]:
generalized_variance = np.exp(np.mean(np.log(np.diag(Q_inv))))  # equation in the paper use daba as 1
generalized_variance #fac in R code

0.4001011304474988

In [25]:
marginal_variances = np.diag(Q_inv/generalized_variance)
marginal_variances

array([1.32361216, 0.76272354, 0.73679649, 0.69877014, 1.44748587,
       3.40641891, 0.90474619, 0.45073465, 1.20607618, 1.80239844,
       0.75840237, 0.58036992])

In [28]:
geometric_mean = np.exp(np.mean(np.log(marginal_variances)))
geometric_mean

1.0

In [30]:
QQ = generalized_variance*Q # this is completely different!
print(np.diag(QQ))

[1.20030339 1.60040452 1.60040452 1.60040452 0.80020226 0.40010113
 1.60040452 2.40060678 1.20030339 0.80020226 1.60040452 2.00050565]
