### Structure matrix (Precision matrix)

#### Scaling testing part

If you have the precision matrix \( Q \) and you want to scale it, you can follow these general steps:

1. **Identify the Null Space \( V \) of \( Q \)**: The null space of \( Q \) contains all vectors that map to zero when multiplied by \( Q \). This can be computed using linear algebra techniques.

2. **Compute Marginal Variances**: Based on the null space constraints, compute the marginal variances. This involves making the precision matrix regular (if necessary) and then applying specific equations to compute the variances.

3. **Calculate Generalized Variance \( \sigma^2_{GV} \)**: Once you have computed the marginal variances, calculate the generalized variance, which represents the overall variability in the spatial component.

4. **Scale the Precision Matrix \( Q \)**: Use the computed generalized variance \( \sigma^2_{GV} \) as a factor to scale the precision matrix \( Q \). This ensures that the scaled precision matrix maintains consistent interpretations across different applications and regions.

Here's a more detailed explanation of each step:

1. **Identify the Null Space \( V \) of \( Q \)**: This involves finding the vectors \( V \) such that \( QV = 0 \). The null space can be computed using linear algebra techniques like eigenvalue decomposition or singular value decomposition.

2. **Compute Marginal Variances**: Once you have identified the null space \( V \), you can compute the marginal variances based on the constraints imposed by \( V \). This typically involves adding a small term to \( Q \) to make it regular, and then using specific equations to compute the variances.

3. **Calculate Generalized Variance \( \sigma^2_{GV} \)**: The generalized variance represents the overall variability in the spatial component of the model. It is computed as the geometric mean of the marginal variances or using other typical values.

4. **Scale the Precision Matrix \( Q \)**: Finally, you can scale the precision matrix \( Q \) by dividing each element by the square root of the generalized variance \( \sigma^2_{GV} \). This ensures that the scaled precision matrix maintains consistent interpretations across different applications and regions.

Implementing these steps in code will depend on the programming language and libraries you're using. Many libraries for linear algebra and spatial analysis provide functions to compute eigenvalues, solve linear equations, and perform matrix operations, which you can use to implement the scaling process.

Python Example to find null space of a Matrix:

In [21]:
from sympy import Matrix 
  
# List A  
A = [[1, 2, 0], [2, 4, 0], [3, 6, 1]] 
  
# Matrix A 
A = Matrix(A) 
  
# Null Space of A 
NullSpace = A.nullspace()   # Here NullSpace is a list 
  
NullSpace = Matrix(NullSpace)   # Here NullSpace is a Matrix 
print("Null Space : ", NullSpace) 

Null Space :  Matrix([[-2], [1], [0]])


In [22]:
print(A * NullSpace) 

Matrix([[0], [0], [0]])


Calculating Determinant of a 2X2 Numpy matrix using numpy.linalg.det() function

In [23]:
# importing Numpy package 
import numpy as np 

# creating a 2X2 Numpy matrix 
n_array = np.array([[50, 29], [30, 44]]) 

# Displaying the Matrix 
print("Numpy Matrix is:") 
print(n_array) 

# calculating the determinant of matrix 
det = np.linalg.det(n_array) 

print("\nDeterminant of given 2X2 matrix:") 
print(int(det)) 


Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


#### Compute marginal variances using an example in Python

This code performs the following steps:

1. Creates an example precision matrix \( Q \).
2. Regularizes the precision matrix \( Q \) by adding a small term to the diagonal.
3. Computes the null space \( V \) of the regularized precision matrix \( Q_{\text{regularized}} \).
4. Computes the orthogonal complement of the null space \( V \).
5. Projects the regularized precision matrix \( Q_{\text{regularized}} \) onto the orthogonal complement of the null space \( V \).
6. Computes the variance-covariance matrix.
7. Extracts the marginal variances, which are the diagonal elements of the variance-covariance matrix.

You can adjust the example precision matrix \( Q \) and the value of \( \epsilon \) as needed for your specific application.

In [25]:
import numpy as np
from scipy.linalg import null_space

# Step 1: Create an example precision matrix Q
Q = np.array([[6, -2, 0],
              [-2, 5, -1],
              [0, -1, 4]])

# Step 2: Make the Precision Matrix Regular (if necessary)
epsilon = 1e-8  # small term to add to the diagonal
Q_regularized = Q + epsilon * np.eye(Q.shape[0])

# Step 3: Compute the Null Space V of Q
V = null_space(Q_regularized)

# Step 4: Compute the orthogonal complement of the null space V
V_perpendicular = np.eye(Q.shape[0]) - V @ np.linalg.pinv(V.T @ V) @ V.T

# Step 5: Project the regularized precision matrix Q_regularized onto the orthogonal complement of the null space V
Q_projected = V_perpendicular @ Q_regularized @ V_perpendicular.T

# Step 6: Compute the variance-covariance matrix
var_cov_matrix = np.linalg.inv(Q_projected)

# Step 7: Extract Marginal Variances (diagonal elements of the variance-covariance matrix)
marginal_variances = np.diag(var_cov_matrix)

print("Marginal Variances:", marginal_variances)

Marginal Variances: [0.19387755 0.24489796 0.26530612]


To find the generalized inverse of a matrix Q, you can use techniques such as singular value decomposition (SVD) or the Moore-Penrose pseudoinverse. 

This code performs the following steps:

1. **Compute SVD of Q**: Singular value decomposition decomposes the matrix \( Q \) into three matrices \( U \), \( S \), and \( V^T \), such that \( Q = U \cdot \text{diag}(S) \cdot V^T \), where \( U \) and \( V \) are orthogonal matrices and \( S \) is a diagonal matrix containing the singular values.

2. **Set Threshold for Singular Values**: We set a threshold value to determine when a singular value is considered nonzero. This is necessary to avoid numerical instability issues.

3. **Calculate Inverse of Singular Values**: We calculate the inverse of the singular values, ensuring that we avoid dividing by very small values close to zero.

4. **Construct the Generalized Inverse**: Using the inverse of singular values obtained in the previous step, we construct the generalized inverse of \( Q \) using the formula \( Q^{-} = V \cdot \text{diag}(1/S_{\text{inv}}) \cdot U^T \).

The resulting matrix \( Q^{-} \) is the generalized inverse of \( Q \).

In [27]:
import numpy as np

# Example matrix Q
Q = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute SVD of Q
U, S, Vt = np.linalg.svd(Q)

# Set threshold for singular values
tol = 1e-12

# Calculate inverse of singular values
S_inv = np.where(S > tol, 1/S, 0)

# Construct the generalized inverse
Q_inv = Vt.T @ np.diag(S_inv) @ U.T

print("Generalized Inverse of Q:")
print(Q_inv)


Generalized Inverse of Q:
[[-6.38888889e-01 -1.66666667e-01  3.05555556e-01]
 [-5.55555556e-02  1.30590700e-16  5.55555556e-02]
 [ 5.27777778e-01  1.66666667e-01 -1.94444444e-01]]


### Generalized variance

In [28]:
import numpy as np

# Example matrix Q
Q = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Get diagonal elements of Q
diagonal_elements = np.diag(Q)

# Take the logarithm of diagonal elements
log_diagonal_elements = np.log(diagonal_elements)

# Sum up the logarithms of diagonal elements
log_sum = np.sum(log_diagonal_elements)

# Divide the sum by the number of rows/columns
n = Q.shape[0]  # Number of rows/columns in Q
mean_log = log_sum / n

# Take the exponent of the mean log
result = np.exp(mean_log)

print("Result:", result)

Result: 3.5568933044900626
